POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "vinhky2012",
    "password": "vinhky2012",
    "email": "vinhky2012@gmail.com",
    "phone": "0982145161"
}
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "vinhky2012",
    "password": "vinhky2012"
}

